apiVersion: v1
kind: Pod
metadata:
  name: pod-limit-checker
spec:
  serviceAccountName: pod-limit-checker-sa
  restartPolicy: Never
  containers:
  - name: checker
    image: docker.io/diablinux/pod-limit-checker:latest
    args:
    - "--namespace"
    - "default"
    - "--verbose"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
