apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-limit-checker-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-limit-checker-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["list", "get"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-limit-checker-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-limit-checker-role
subjects:
- kind: ServiceAccount
  name: pod-limit-checker-sa
  namespace: default
